language: python
cache: pip

python:
  - "3.5"
  - "2.7"

env:
  - DJANGO="django>=1.11,<1.12"
  - DJANGO="django>=2.0,<2.1"
  - DJANGO="django>=2.1,<2.2"

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO="django>=2.0,<2.1"
    - python: "2.7"
      env: DJANGO="django>=2.1,<2.2"

branches:
  only:
    - master

before_install:
  - pip install -U pip wheel setuptools
  - pip install --no-cache-dir -U -r requirements-test.txt

install:
  - pip install https://github.com/openwisp/openwisp-users/tarball/master
  - pip install $DJANGO
  - pip install -e .[users] .[qa]

before_script:
  - openwisp-utils-qa-checks --migration-path "./tests/test_project/migrations"

script:
  - coverage run --source=openwisp_utils runtests.py

after_success:
  coveralls
